# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the (log-)likelihood of the conditional extremes distribution when
#' a and b are given. We assume that a has already been subtracted from x,
#' i.e. x = (y - a) for some observations y.
#' Further, we assume that b does not depend on y0, meaning that we only need one
#' value of b for each distance, instead of a matrix B that has one value for each
#' pair of distance and threshold exceedance y0.
#' 
#' The input variables are:
#' x: an (n x d)-dimensional matrix of observations where a has already been subtracted.
#' A: The projection matrix used for building the SPDE approximation
#' b: An m-dimensional vector containing the values of b at the m triangular mesh nodes.
#' sigma0: The covariance matrix of the m Gaussian random variables in the triangular mesh.
#' nugget: The variance of the nugget effect.
#' logd: Boolean explaining if we should return the log-likelihood or the likelihood.
#' na_rm: Boolean explaining how we should treat NA values. If na_rm = false, then
#'   any column of x that returns an NA value will result in an NA value in the output.
#'   If na_rm = true, then we remove the NA values before computing the likelihood.
#'   So if e.g. a column has 3 NA variables, then we remove these, and then we compute
#'   the likelihood for a (d-3)-dimensional Gaussian random variable.
dconditional_no_beta <- function(x, A, b, sigma0, nugget, logd = TRUE, na_rm = TRUE) {
    .Call(`_spatialConditionalExtremes_dconditional_no_beta`, x, A, b, sigma0, nugget, logd, na_rm)
}

#' Compute the (log-)likelihood of the conditional extremes distribution when
#' a and b are given. We assume that a has already been subtracted from x,
#' i.e. x = (y - a) for some observations y.
#' 
#' The input variables are:
#' x: an (n x d)-dimensional matrix of observations where a has already been subtracted.
#' A: The projection matrix used for building the SPDE approximation
#' B: An (m x n)-dimensional matrix containing the values of b at the m triangular mesh nodes,
#'   for each of the n threshold exceedances at the conditioning sites of interest
#' sigma0: The covariance matrix of the m Gaussian random variables in the triangular mesh.
#' nugget: The variance of the nugget effect.
#' logd: Boolean explaining if we should return the log-likelihood or the likelihood.
#' na_rm: Boolean explaining how we should treat NA values. If na_rm = false, then
#'   any column of x that returns an NA value will result in an NA value in the output.
#'   If na_rm = true, then we remove the NA values before computing the likelihood.
#'   So if e.g. a column has 3 NA variables, then we remove these, and then we compute
#'   the likelihood for a (d-3)-dimensional Gaussian random variable.
dconditional <- function(x, A, B, sigma0, nugget, logd = TRUE, na_rm = TRUE) {
    .Call(`_spatialConditionalExtremes_dconditional`, x, A, B, sigma0, nugget, logd, na_rm)
}

dconditional2 <- function(x, A, B, B2, sigma0, nugget, logd = TRUE, na_rm = TRUE) {
    .Call(`_spatialConditionalExtremes_dconditional2`, x, A, B, B2, sigma0, nugget, logd, na_rm)
}

